<a href="https://colab.research.google.com/github/Mgobeaalcoba/proyectos_platzi/blob/main/Ejercicios_de_Funciones_Lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios de Funciones Lineales Resueltos


In [1]:
import numpy as np

**Ejercicio.** Determina si las siguientes funciones son lineales o no:

* $ g(\mathbf{x}) = x_{0}$

* $f2(\mathbf{x}) = x_{n-1} - x_{0}$

* Si $\mathbf{x}\in\mathbb{R}^{4}$ y $f:\mathbb{R}^{4} \to \mathbb{R}$ definida como $f3(\mathbf{x})=x_{3}+(x_{3}-x_{2})$




Si la función $g$ cumple que $g(\alpha\mathbf{x}+\beta\mathbf{y}) = \alpha g(\mathbf{x})+\beta g(\mathbf{y})$ decimos que la función $g$ es una **función lineal.** 


In [ ]:
def g(x):
    return x[0]

In [ ]:
x = np.array([2,1,0,-1])
y = np.array([4,1,2,3])
alfa = 2
betha = -2
print(g(alfa*x))
print(g(betha*y))
print(g(alfa*x+betha*y))
print(alfa*g(x)+betha*g(y)) # Debe dar igual que la de arriba para comprobar que sean lineales

4
-8
-4
-4


In [ ]:
def f2(x):
  return x[len(x)-1]-x[0]

In [ ]:
def f3(x):
  return x[3]+(x[3]-x[2])

In [ ]:
a = np.array([5,3,-2,7])
b = np.array([6,-5,-2,9])

In [ ]:
print(f2(a))
print(f2(b))
print(f3(a))
print(f3(b))

2
3
16
20


In [ ]:
print(f2(alfa*a+betha*b))
print(alfa*f2(a)+betha*f2(b)) # Debe ser igual que la de arriba para que sea una función lineal f2. Cumple con la propiedad de la superposición.
print(f3(alfa*a+betha*b))
print(alfa*f3(a)+betha*f3(b)) # Debe ser igual que la de arriba para que sea una función lineal f3. Cumple con la propiedad de la superposición.

-2
-2
-8
-8


**Problema: Potencia en un clúster de procesadores y temperatura.** La temperatura $T$ de un cluster de tres procesadores es una función afín de la potencia de los procesadores $P^T = [P_{0}\; P_{1}\; P_{2}]$. Cuando los tres procesadores están en reposo tenemos que $P^T = [10\; 10\; 10]$ lo cual nos da una temperatura de $T=35$. Cuando el primer procesador opera a potencia absoluta tenemos que $P^T = [100\; 10\; 10]$ y la temperatura se eleva a $T=60$. Cuando el segundo procesador opera a su máxima capacidad tenemos $P^T = [10\; 100\; 10]$ y la temperatura se eleva a $T=75$. Cuando el tercer procesador opera a máxima potencia mientras que los otros dos están en reposo tenemos que $P^T = [10\; 10\; 100]$ y la temperatura se elevea a $T=65$. Supongamos que los tres procesadores operan a máxima potencia ¿Qué temperatura se alcanza? La temperatura de fusión de los procesadores (a la que los procesadores se derriten) es cerca de $150$ ¿Cuál es la potencia máxima que pueden alcanzar los procesadores para que $T\le 150$?  
*Hint:* $T(P) = a^T P + b$

Dado que sabemos que la temperatura es función afín, se puede ver de la siguiente forma:

* $T(P)=a^TP+b$

Dado que *P*, es un vector en $\mathbb{R}^3$, la expresión anterior se puede ver en forma vectorial como:

$$
T(P) = [a_{0},a_{1},a_{2}] \begin{bmatrix}P_{0}\\ P_{1}\\P_{2}\end{bmatrix} + b = a_{0}P_{0}+a_{1}P_{1}+a_{2}P_{2} + b
$$

Notemos que el problema nos ofrece 4 soluciones para esta ecuación:

* $10a_{0}+10a_{1}+10a_{2}+b=35$
* $100a_{0}+10a_{1}+10a_{2}+b=60$
* $10a_{0}+100a_{1}+10a_{2}+b=75$
* $10a_{0}+10a_{1}+100a_{2}+b=65$

Con los cuales debemos encontrar los valores de $a_{0},a_{1},a_{2} y b$, por lo que podemos proceder a resolverlo como un sistema de ecuaciones 4x4.


In [86]:
x1 = np.array([10,10,10])
x2 = np.array([100,10,10])
x3 = np.array([10,100,10])
x4 = np.array([10,10,100])
suma_x = x1+x2+x3+x4
promedio_x = (x1+x2+x3+x4)/4
print(suma_x)
print(promedio_x)

[130 130 130]
[32.5 32.5 32.5]


In [115]:
vector = np.array([[35],[60],[75],[65]])
vector

array([[35],
       [60],
       [75],
       [65]])

In [170]:
matriz = np.array([[10,100,10,10], # Cargo los valores de cada ecuación lineal en columnas no en filas
                   [10,10,100,10],
                   [10,10,10,100],
                   [1,1,1,1]])
matriz

array([[ 10, 100,  10,  10],
       [ 10,  10, 100,  10],
       [ 10,  10,  10, 100],
       [  1,   1,   1,   1]])

In [131]:
matriz.T

array([[ 10,  10,  10,   1],
       [100,  10,  10,   1],
       [ 10, 100,  10,   1],
       [ 10,  10, 100,   1]])

In [155]:
vector2 = vector.T.dot(np.linalg.inv(matriz))
vector2

array([[ 0.27777778,  0.44444444,  0.33333333, 24.44444444]])

In [162]:
# Los tres primeros son los valores de a0, a1 y a2 y el ultimo es el valor de b
a = vector2[:,:3]
b = vector2[:,3]
print(a)
print(b)

[[0.27777778 0.44444444 0.33333333]]
[24.44444444]


In [163]:
# comprobación

print(vector2.dot(matriz))
print(vector.T) # Son iguales, por lo que encontre el valor de mis variables calculando el producto interno entre mi vector de resultado transpuesto y mi matriz invertida

[[35. 60. 75. 65.]]
[[35 60 75 65]]


In [175]:
def T(x): # Función de temperatura
  return a.dot(x)+b

In [177]:
# funcion de temperatura

tx4 = T(x4)
tx3 = T(x3)
tx2 = T(x2)
tx1 = T(x1)
print(tx1)
print(tx2)
print(tx3)
print(tx4)

[35.]
[60.]
[75.]
[65.]


In [178]:
#Supongamos que los tres procesadores operan a máxima potencia 
#¿Qué temperatura se alcanza?
max_temp = np.array([[100],
                     [100],
                     [100]])
tmax = T(max_temp)
print(tmax)

[[130.]]


In [182]:
# La temperatura de fusión de los procesadores (a la que los procesadores se derriten) 
#es cerca de 150 ¿Cuál es la potencia máxima que pueden alcanzar los procesadores para que T<=150?  

#asumiendo la temperatura máxima para los 3 procesadores sea la misma, con una tolerancia de 0.01

var=0.0001
min=100.0 # Minimo de potencia
max=150.0 # Maximo de potencia

potencia_prueba = np.array([[min],
                            [min],
                            [min]])
while T(potencia_prueba) < 150:
  max_potencia = potencia_prueba
  potencia_prueba += var

print(max_potencia)


[[118.9474]
 [118.9474]
 [118.9474]]
