<a href="https://colab.research.google.com/github/Mgobeaalcoba/proyectos_platzi/blob/main/Proyecto_An%C3%A1lisis_de_sentimientos_en_tweets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = "Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!"
b = "Vaya señora que bueno que se asesora por alguien inteligente no por el ignorante del Gatt."
c = "Se me ocurre y sin ver todos los videos de Plazti que me informéis por dónde empiezo. Entiendo que os tendría que decir quién soy y que quiero, vamos conocerme para asesorarme bien. Un saludo"
d = "Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!"


In [3]:
def a_lista(string):
  string = string.replace("!"," ").lower()
  lista = string.replace("!","").replace(",","").replace(".","").replace("(","").replace(")","").split(" ")
  return lista

In [4]:
def contador(referencias, tweets):
  i = 0
  vector_palabras = []
  for referencia in referencias:
    for palabra in tweets:
      if referencia == palabra:
        i += 1
    vector_palabras.append(i)
    i = 0
  return vector_palabras

In [5]:
def clasificador(criterio1, criterio2, criterio3, tweets):
  i = 0
  vector_palabras = []
  for criterio in criterio1:
    for palabra in tweets:
      if criterio == palabra:
        i += 1
  vector_palabras.append(i)
  i = 0
  for criterio in criterio2:
    for palabra in tweets:
      if criterio == palabra:
        i += 1
  vector_palabras.append(i)
  i = 0
  for criterio in criterio3:
    for palabra in tweets:
      if criterio == palabra:
        i += 1
  vector_palabras.append(i)  
  return vector_palabras

In [6]:
list_a = a_lista(a)
list_b = a_lista(b)
list_c = a_lista(c)
list_d = a_lista(d)

In [7]:
print(list_a)
print(list_b)
print(list_c)
print(list_d)

['gran', 'mexicano', 'y', 'excelente', 'en', 'su', 'área', 'su', 'muerte', 'es', 'una', 'enorme', 'perdida', 'y', 'debería', 'ser', 'luto', 'nacional', '', '', '']
['vaya', 'señora', 'que', 'bueno', 'que', 'se', 'asesora', 'por', 'alguien', 'inteligente', 'no', 'por', 'el', 'ignorante', 'del', 'gatt']
['se', 'me', 'ocurre', 'y', 'sin', 'ver', 'todos', 'los', 'videos', 'de', 'plazti', 'que', 'me', 'informéis', 'por', 'dónde', 'empiezo', 'entiendo', 'que', 'os', 'tendría', 'que', 'decir', 'quién', 'soy', 'y', 'que', 'quiero', 'vamos', 'conocerme', 'para', 'asesorarme', 'bien', 'un', 'saludo']
['soy', 'docente', 'universitario', 'estoy', 'intentando', 'preparar', 'mis', 'clases', 'en', 'modo', 'platzi', 'bien', 'didáctico', 'le', 'llamo', 'modo', 'noticiero', 'descargue', 'una', 'plataforma', 'gratuita', 'de', 'grabación', 'y', 'transmisión', 'de', 'vídeo', 'se', 'llama', 'obs', 'estudio', 'bueno', 'la', 'sigo', 'remando', 'con', 'sus', 'funciones', 'pero', 'sé', 'que', 'saldrá', 'algo', 

In [8]:
buscadas = ["muerte", "perdida", "luto", "excelente" , "gran" , "positivo", "bueno", "inteligente", "ignorante", "quiero", "bien", "didáctico", "bueno", "remando", "saldrá"]

In [13]:
cuenta_cadena_a = contador(buscadas,list_a) 
cuenta_cadena_b = contador(buscadas,list_b)
cuenta_cadena_c = contador(buscadas,list_c)
cuenta_cadena_d = contador(buscadas,list_d)

print(cuenta_cadena_a)
print(cuenta_cadena_b)
print(cuenta_cadena_c)
print(cuenta_cadena_d)

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1]


In [10]:
positivas = ["excelente","gran","positivo","bueno","inteligente","quiero","bien","didático","bueno","saldrá"]
negativas = ["muerte","perdida","luto","ignorante"]
neutras = ["remando","saldrá"]

In [17]:
clasifica_cadena_a = clasificador(positivas,neutras,negativas,list_a)
clasifica_cadena_b = clasificador(positivas,neutras,negativas,list_b)
clasifica_cadena_c = clasificador(positivas,neutras,negativas,list_c)
clasifica_cadena_d = clasificador(positivas,neutras,negativas,list_d)

print(clasifica_cadena_a)
print(clasifica_cadena_b)
print(clasifica_cadena_c)
print(clasifica_cadena_d)

[2, 0, 3]
[3, 0, 1]
[2, 0, 0]
[4, 2, 0]


In [29]:
calidad_a = sum(cuenta_cadena_a)/len(cuenta_cadena_a)
calidad_b = sum(cuenta_cadena_b)/len(cuenta_cadena_b)
calidad_c = sum(cuenta_cadena_c)/len(cuenta_cadena_c)
calidad_d = sum(cuenta_cadena_d)/len(cuenta_cadena_d)
print(calidad_a)
print(calidad_b)
print(calidad_c)
print(calidad_d)
calidad_promedio = sum(cuenta_cadena_a+cuenta_cadena_b+cuenta_cadena_c+cuenta_cadena_d)/len(cuenta_cadena_a+cuenta_cadena_b+cuenta_cadena_c+cuenta_cadena_d)
print(calidad_promedio)

0.3333333333333333
0.26666666666666666
0.13333333333333333
0.4
0.2833333333333333


In [20]:
avg_sentimiento_a = sum(clasifica_cadena_a)/len(clasifica_cadena_a)
avg_sentimiento_b = sum(clasifica_cadena_b)/len(clasifica_cadena_b)
avg_sentimiento_c = sum(clasifica_cadena_c)/len(clasifica_cadena_c)
avg_sentimiento_d = sum(clasifica_cadena_d)/len(clasifica_cadena_d)
print(avg_sentimiento_a)
print(avg_sentimiento_b)
print(avg_sentimiento_c)
print(avg_sentimiento_d)

1.6666666666666667
1.3333333333333333
0.6666666666666666
2.0


In [23]:
array_sentimiento_a = np.array(clasifica_cadena_a)
array_sentimiento_b = np.array(clasifica_cadena_b)
array_sentimiento_c = np.array(clasifica_cadena_c)
array_sentimiento_d = np.array(clasifica_cadena_d)
print(array_sentimiento_a)
print(array_sentimiento_b)
print(array_sentimiento_c)
print(array_sentimiento_d)


[2 0 3]
[3 0 1]
[2 0 0]
[4 2 0]


In [24]:
array_score = np.array([1,0,-1])
print(array_score)

[ 1  0 -1]


In [26]:
prod_int_score_a = array_score.T.dot(array_sentimiento_a)
prod_int_score_b = array_score.T.dot(array_sentimiento_b)
prod_int_score_c = array_score.T.dot(array_sentimiento_c)
prod_int_score_d = array_score.T.dot(array_sentimiento_d)
print(prod_int_score_a)
print(prod_int_score_b)
print(prod_int_score_c)
print(prod_int_score_d)

-1
2
2
4


In [27]:
print(calidad_a)
print(calidad_b)
print(calidad_c)
print(calidad_d)
print()
print(avg_sentimiento_a)
print(avg_sentimiento_b)
print(avg_sentimiento_c)
print(avg_sentimiento_d)
print()
print(prod_int_score_a)
print(prod_int_score_b)
print(prod_int_score_c)
print(prod_int_score_d)
print()

0.3333333333333333
0.26666666666666666
0.13333333333333333
0.4

1.6666666666666667
1.3333333333333333
0.6666666666666666
2.0

-1
2
2
4



* ¿Qué tuit es más positivo?

* ¿Qué tuit es más negativo?

* ¿Cuál es tu calidad promedio?

* ¿Cómo interpretas $avg(\vec{s})$ y $score(\vec{s})$?

* ¿Cómo relacionas la calidad con $score(\vec{s})$ y $avg(\vec{s})$?

El cuarto tweet es mas positivo ya que tanto el promedio de sentimiento como el score sentimental son mas altos.

El primer twwet es el mas negativo ya que el score sentimental es el único negativo, lo que significa que tiene una mayor carga de palabras negativas que positivas.

Mi calidad promedio es 0,28 %

El promedio de sentimiento muestra la carga sentimental del tweet sin tomar en cuenta si la misma es positiva o negativa. El score en cambio demuestra el caracter de esa carga valorativa tomando valores positivos si la carga valorativa es buena y negativas si es mala. Si el score se acerca a 0 la carga valorativa es neutra. 

A mayor calidad mayor promedio de sentimiento. No encuentro una relación lineal entre la calidad y el score ya que al caer algunas palabras en el campo neutro las mismas anulan la relación que se establece entre la calidad y el promedio de sentimiento. 



